### ISSUE TITLE
Extend the api

### ISSUE THREAD

**Issue by kageurufu** [scottrice/ConsoleGrid#18]
I would like to be able to submit images through an API, as well as some sort of fulltext fuzzy searching. I may fork and write this if I have the time

**Comment by scottrice** [comment]
Just added the beginnings of V2 of the API. This gives a lot more information than the single API request that used to be available.

Letting people upload images and such through the API is not currently on my todo list through. As of right now the API is read only. I'm not opposed to making it readwrite in the future, but I need to put a lot more thought into how that will be accomplished over my current implementation which is just meant to expose the data to consumers.
