### ISSUE TITLE
Can't communicate to the API via AJAX

### ISSUE THREAD

**Issue by ClickInspire** [scottrice/ConsoleGrid#28]
I'm trying to make an AJAX request to `/api/top_picture` and am getting back:

> No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.

This can be solved by adding that header in and settings it to `*`. Without I'm not sure I can get the AJAX to work...

Is this something you would consider supporting?

**Comment by scottrice** [comment]
Ah, I completely forgot about that. I will definitely add that in, as AJAX access to the API is really important.
