### ISSUE TITLE
Is Console grid search down?

### ISSUE THREAD

**Issue by iantpryor** [scottrice/ConsoleGrid#34]
Can't pull images using ice, can't search on consolegrid.com -  "We're sorry, something wen't wrong." error.  

Can still go to individual game pages, ie http://consolegrid.com/games/438 still shows the Metroid game page.

**Comment by TypeDan** [comment]
I'm getting the same thing, Ian :(

**Comment by CubeFusion** [comment]
This is likely a duplicate of issue #16 
Apparently the Apache Solr application powering the sites search is crashing, and has to be manually restarted.

**Comment by Hunk4TH** [comment]
Same problem here. Hopefully the server can be restarted soon.

**Comment by StormPooper** [comment]
Looks like it's still happening, which is preventing Ice from retrieving game images (scottrice/Ice#322).

**Comment by Hunk4TH** [comment]
Same problem here...

**Comment by jawshey** [comment]
So we're nearing the two week mark now since ConsoleGrid went down - are there any updates? :(

**Comment by scottrice** [comment]
I'm aware of the issue, but due to the holidays and some technical problems I'm unable to get a fix out for a couple days. Hoping to restore service soon.

**Comment by jawshey** [comment]
Excellent! Wishing a happy new year to you Scott!

**Comment by TypeDan** [comment]
Sweet, look forward to it. Happy new year

**Comment by Hunk4TH** [comment]
Awesome news Scott happy new year!

**Comment by scottrice** [comment]
Alright, ConsoleGrid should be back up. Sorry for the delay, and thanks for the patience. Let me know if you run into any more issues!

**Comment by ghost** [comment]
Thank you, have a good one

Kind Regards,

Daniel
