### ISSUE TITLE
Need a new maintainer?

### ISSUE THREAD

**Issue by nateberkopec** [scottrice/ConsoleGrid#37]
Hey, it looks like this part of the ICE ecosystem hasn't gotten a lot of love lately. I'm a big ICE user and love it, but it looks like ConsoleGrid has some ongoing issues that could use some attention. 

I'm happy to take over ConsoleGrid, both on the open-source maintainer side and on the deployment side.

I've taken over a few projects in the past like `terminal-table` and `raven-ruby`, see my GH profile. My email is there too.

**Comment by scottrice** [comment]
@nateberkopec - That would be amazing. As time has gone on I've had less and less free time to spend on side projects, and what little time I do have is normally spent on Ice itself. I would love someone to help out with ConsoleGrid, as it is a pretty important point of the Ice ecosystem.

Next step wise, I think there are two things:
- Give you commit access to the repo - I will do that now
- Provide some way to give you access to the production EC2 instance. This I'm less sure on how to make it work, but would be happy to chat with you about it (my email is meris608@gmail.com if you'd like, although I'm not great at responding to emails. The most reliable way to contact me is probably Messenger/Facebook - my username is sar).

Thanks a bunch for offering to do this - ConsoleGrid is in desperate need of some love and I'm not able to provide it. I really appreciate your help.

**Comment by nateberkopec** [comment]
Send a Facebook request, sounds good!
